@extends('layouts.admin')
@section('title', $service->exists ? 'Edit Service' : 'Add Service')
@section('content')
<div class="card form">
    <form method="post" action="{{ $service->exists ? route('admin.services.update',$service) : route('admin.services.store') }}">
        @csrf
        @if($service->exists) @method('PUT') @endif
        <div class="field"><label>Customer *</label><select class="input" name="customer_id" required><option value="">Select customer</option>@foreach($customers as $x)<option value="{{ $x->id }}" @selected((int)old('customer_id',$service->customer_id)===$x->id)>{{ $x->name }}</option>@endforeach</select></div>
        <div class="field"><label>Service Type *</label><select class="input" id="service_type_id" name="service_type_id" required>@foreach($serviceTypes as $x)<option value="{{ $x->id }}" data-code="{{ $x->code }}" @selected((int)old('service_type_id',$service->service_type_id)===$x->id) data-terms='@json($x->terms->pluck("months")->values())'>{{ $x->name }}</option>@endforeach</select></div>
        <div class="field"><label>Service Name *</label><input class="input" name="service_name" value="{{ old('service_name',$service->service_name) }}" required></div>
        <div class="field"><label>Value</label><input class="input" name="value" id="service_value" value="{{ old('value',$service->value) }}" placeholder="Domain / IP / license / contract number..."></div>
        <div class="field"><label>Provider</label><select class="input" name="provider_id"><option value="">Select provider</option>@foreach($providers as $x)<option value="{{ $x->id }}" @selected((int)old('provider_id',$service->provider_id)===$x->id)>{{ $x->name }}</option>@endforeach</select></div>
        <div class="field"><label>Service Cost</label><div style="display:flex;gap:8px"><input class="input" style="flex:1" type="number" min="0" step="0.01" name="cost_amount" value="{{ old('cost_amount',$service->cost_amount) }}" placeholder="500000"><select class="input" style="width:110px" name="cost_currency"><option value="VND" @selected(old('cost_currency',$service->cost_currency ?: 'VND')==='VND')>VND</option><option value="USD" @selected(old('cost_currency',$service->cost_currency)==='USD')>USD</option><option value="EUR" @selected(old('cost_currency',$service->cost_currency)==='EUR')>EUR</option></select></div><small class="muted">Chi phí thực tế của dịch vụ theo chu kỳ thanh toán.</small></div>
        <div class="field"><label>Billing Cycle</label><select class="input" name="cost_billing_cycle"><option value="monthly" @selected(old('cost_billing_cycle',$service->cost_billing_cycle ?: 'monthly')==='monthly')>Monthly</option><option value="quarterly" @selected(old('cost_billing_cycle',$service->cost_billing_cycle)==='quarterly')>Quarterly</option><option value="yearly" @selected(old('cost_billing_cycle',$service->cost_billing_cycle)==='yearly')>Yearly</option><option value="one_time" @selected(old('cost_billing_cycle',$service->cost_billing_cycle)==='one_time')>One-time</option></select></div>
        <div id="monitoring-fields" style="display:none">
            <div class="field"><label>WAN IP / Monitor Target *</label><input class="input" id="monitor_target" name="monitor_target" value="{{ old('monitor_target',$service->monitor_target) }}" placeholder="118.69.xxx.xxx"><small class="muted">IP WAN của đường FTTH cần giám sát.</small></div>
            <div class="field"><label>Check Method</label><select class="input" id="monitor_check_method" name="monitor_check_method"><option value="">Disabled</option><option value="ping" @selected(old('monitor_check_method',$service->monitor_check_method)==='ping')>PING</option><option value="port" @selected(old('monitor_check_method',$service->monitor_check_method)==='port')>Check Port</option></select></div>
            <div class="field" id="monitor-port-field" style="display:none"><label>Check Port *</label><input class="input" id="monitor_port" type="number" min="1" max="65535" name="monitor_port" value="{{ old('monitor_port',$service->monitor_port) }}" placeholder="443"></div>
            <div class="field"><label>Check Interval</label><select class="input" name="monitor_interval_seconds"><option value="30" @selected((int)old('monitor_interval_seconds',$service->monitor_interval_seconds ?: 60)===30)>30 seconds</option><option value="60" @selected((int)old('monitor_interval_seconds',$service->monitor_interval_seconds ?: 60)===60)>1 minute</option><option value="300" @selected((int)old('monitor_interval_seconds',$service->monitor_interval_seconds ?: 60)===300)>5 minutes</option><option value="600" @selected((int)old('monitor_interval_seconds',$service->monitor_interval_seconds ?: 60)===600)>10 minutes</option></select></div>
            <div class="field"><label>Timeout</label><select class="input" name="monitor_timeout_seconds"><option value="3" @selected((int)old('monitor_timeout_seconds',$service->monitor_timeout_seconds ?: 5)===3)>3 seconds</option><option value="5" @selected((int)old('monitor_timeout_seconds',$service->monitor_timeout_seconds ?: 5)===5)>5 seconds</option><option value="10" @selected((int)old('monitor_timeout_seconds',$service->monitor_timeout_seconds ?: 5)===10)>10 seconds</option></select></div>
        </div>
        <div class="field"><label>Service Term</label><select class="input" id="service_term_months" name="service_term_months"></select></div>
        <div class="field"><label>Expiry Date</label><div style="display:flex;gap:8px;align-items:center"><input class="input" style="flex:1" id="expiry_date" type="date" name="expiry_date" value="{{ old('expiry_date', optional($service->expiry_date)->format('Y-m-d')) }}"><button type="button" class="btn gray" id="detect-expiry" style="display:none;white-space:nowrap">🔎 Detect Expiry</button></div><small class="muted" id="expiry-help">Leave blank for services without an expiry date.</small><div id="detect-result" class="muted" style="margin-top:6px"></div></div>
        <div class="field"><label>Alert Policy</label><select class="input" id="alert_policy_id" name="alert_policy_id"><option value="">Select policy</option>@foreach($policies as $x)<option value="{{ $x->id }}" data-type="{{ $x->service_type_id }}" @selected((int)old('alert_policy_id',$service->alert_policy_id)===$x->id)>{{ $x->name }}</option>@endforeach</select></div>
        <div class="field"><label>Responsible IT</label><select class="input" name="responsible_it_id"><option value="">Select user</option>@foreach($responsibleUsers as $x)<option value="{{ $x->id }}" @selected((int)old('responsible_it_id',$service->responsible_it_id)===$x->id)>{{ $x->name }}</option>@endforeach</select></div>
        <div class="field"><label>Status *</label><select class="input" name="status" required><option value="active" @selected(old('status',$service->status)==='active')>Active</option><option value="suspended" @selected(old('status',$service->status)==='suspended')>Suspended</option><option value="expired" @selected(old('status',$service->status)==='expired')>Expired</option></select></div>
        <div class="field"><label><input type="checkbox" name="auto_renew" value="1" @checked(old('auto_renew',$service->auto_renew))> Auto Renew</label></div>
        <div class="field"><label>Note</label><textarea class="input" name="note" rows="4">{{ old('note',$service->note) }}</textarea></div>
        <div class="actions"><button class="btn" type="submit">Save</button><a class="btn gray" href="{{ route('admin.services.index') }}">Cancel</a></div>
    </form>
</div>
<script>
(function(){
 const type=document.getElementById('service_type_id'),term=document.getElementById('service_term_months'),expiry=document.getElementById('expiry_date'),policy=document.getElementById('alert_policy_id');
 const method=document.getElementById('monitor_check_method'),target=document.getElementById('monitor_target'),port=document.getElementById('monitor_port'),monitoring=document.getElementById('monitoring-fields'),portField=document.getElementById('monitor-port-field');
 const detect=document.getElementById('detect-expiry'),result=document.getElementById('detect-result'),value=document.getElementById('service_value');
 let currentTerm='{{ old('service_term_months',$service->service_term_months) }}',currentPolicy='{{ old('alert_policy_id',$service->alert_policy_id) }}',currentMethod='{{ old('monitor_check_method',$service->monitor_check_method) }}';
 function refresh(){const opt=type.options[type.selectedIndex];let terms=[];try{terms=JSON.parse(opt?.dataset.terms||'[]')}catch(e){}term.innerHTML='<option value="">No term</option>'+terms.map(m=>'<option value="'+m+'" '+(String(m)===String(currentTerm)?'selected':'')+'>'+m+' tháng</option>').join('');[...policy.options].forEach(o=>{if(!o.value)return;const ok=o.dataset.type===type.value;o.hidden=!ok;if(!ok&&o.selected)o.selected=false;});if([...policy.options].some(o=>o.value===String(currentPolicy)&&!o.hidden))policy.value=currentPolicy;const code=String(opt?.dataset.code||'').toUpperCase();const isInternet=code==='INTERNET';const isDomain=code==='DOMAIN';monitoring.style.display=isInternet?'block':'none';detect.style.display=isDomain?'inline-block':'none';if(isInternet){method.value=currentMethod||method.value||'';portField.style.display=method.value==='port'?'block':'none';port.required=method.value==='port';}else{method.value='';target.value='';port.value='';portField.style.display='none';port.required=false;}syncExpiryFields();}
 function syncExpiryFields(){const hasExpiry=!!expiry.value;term.required=hasExpiry;policy.required=hasExpiry;term.disabled=!hasExpiry;policy.disabled=!hasExpiry;if(!hasExpiry){term.value='';policy.value='';}}
 type.addEventListener('change',()=>{currentTerm='';currentPolicy='';currentMethod='';result.textContent='';refresh();});
 method?.addEventListener('change',()=>{currentMethod=method.value;portField.style.display=method.value==='port'?'block':'none';port.required=method.value==='port';if(method.value!=='port')port.value='';});
 expiry.addEventListener('change',syncExpiryFields);
 detect.addEventListener('click',async()=>{if(!{{ $service->exists?'true':'false' }}){result.textContent='Save the service first, then Detect Expiry.';return;}detect.disabled=true;detect.textContent='Detecting...';result.textContent='';try{const r=await fetch('{{ $service->exists ? route('admin.services.detect_expiry',$service) : '#' }}',{method:'POST',headers:{'X-CSRF-TOKEN':'{{ csrf_token() }}','Accept':'application/json'}});const d=await r.json();if(d.ok&&d.result?.saved_expiry_date){expiry.value=d.result.saved_expiry_date;result.textContent='Detected: '+d.result.saved_expiry_date+(d.result.days_remaining!=null?' ('+d.result.days_remaining+' days remaining)':'');syncExpiryFields();}else{result.textContent=d.result?.error||d.message||'Could not detect domain expiry.';}}catch(e){result.textContent='Detect failed: '+e.message;}finally{detect.disabled=false;detect.textContent='🔎 Detect Expiry';}});
 refresh();
})();
</script>
@endsection
