@extends('layouts.admin')
@section('title','PC Audit - Audit Code')
@section('content')
<div class="card"><div style="display:flex;justify-content:space-between;align-items:center;gap:10px;flex-wrap:wrap"><div><h2>PC Audit — Audit Code</h2><p class="muted">Mỗi Code gắn với một Chi nhánh. Tool dùng Code để xác định Customer/Branch.</p></div><div><a class="button" href="{{ route('admin.pc_audit.settings') }}">Cấu hình Tool</a> <a class="button" href="{{ route('admin.pc_audit.recipients') }}">Email Customer</a></div></div></div>
@if(session('success'))<div class="card" style="margin-top:14px">{{ session('success') }}</div>@endif
<div class="card" style="margin-top:18px"><h3>Tạo Audit Code</h3><form method="POST" action="{{ route('admin.pc_audit.codes.store') }}">@csrf<div style="display:grid;grid-template-columns:2fr 2fr 2fr auto;gap:12px;align-items:end"><div><label>Customer / Chi nhánh</label><select name="branch_id" required><option value="">-- Chọn chi nhánh --</option>@foreach($branches as $branch)<option value="{{ $branch->id }}">{{ $branch->customer?->name }} — {{ $branch->name }}</option>@endforeach</select></div><div><label>Tên Code</label><input name="name" placeholder="Ví dụ: Audit máy ABC"></div><div><label>Code (để trống = tự sinh)</label><input name="code" placeholder="ABC-2026"></div><button type="submit">Tạo Code</button></div></form></div>
<div class="card" style="margin-top:18px"><form method="GET" style="display:flex;gap:10px;align-items:end;flex-wrap:wrap"><div><label>Customer</label><select name="customer_id" onchange="this.form.submit()"><option value="">Tất cả</option>@foreach($customers as $customer)<option value="{{ $customer->id }}" @selected((string)$customerId===(string)$customer->id)>{{ $customer->name }}</option>@endforeach</select></div><div style="flex:1"><label>Tìm Code</label><input name="search" value="{{ $search }}" placeholder="Code / tên"></div><button type="submit">Lọc</button></form></div>
<div class="card" style="margin-top:18px"><table style="width:100%;border-collapse:collapse"><thead><tr><th>Code</th><th>Tên</th><th>Customer</th><th>Chi nhánh</th><th>Trạng thái</th><th></th></tr></thead><tbody>@forelse($codes as $code)<tr><td><strong>{{ $code->code }}</strong></td><td>{{ $code->name }}</td><td>{{ $code->branch?->customer?->name }}</td><td>{{ $code->branch?->name }}</td><td>{{ $code->is_active ? 'Đang dùng' : 'Đã khóa' }}</td><td><form method="POST" action="{{ route('admin.pc_audit.codes.toggle',$code) }}">@csrf @method('PATCH')<button type="submit">{{ $code->is_active ? 'Khóa' : 'Kích hoạt' }}</button></form></td></tr>@empty<tr><td colspan="6">Chưa có Audit Code.</td></tr>@endforelse</tbody></table><div style="margin-top:14px">{{ $codes->links() }}</div></div>
@endsection
