@extends('layouts.admin')
@section('title','Job Titles')
@section('content')
<div class="card">
 <div style="display:flex;justify-content:space-between;align-items:center;gap:12px;margin-bottom:15px;flex-wrap:wrap"><div><strong>Job Title Management</strong><div class="muted">Define job titles and the Target Workload Point used by KPI calculation.</div></div><div class="actions">@if(auth()->user()->hasPermission('job_titles.import'))<a class="btn gray" href="{{ route('admin.job_titles.template') }}">Download Import Template</a>@endif @if(auth()->user()->hasPermission('job_titles.export'))<a class="btn gray" href="{{ route('admin.job_titles.export',request()->only('search','show_hidden')) }}">Export Excel</a>@endif @if(auth()->user()->hasPermission('job_titles.import'))<form method="post" action="{{ route('admin.job_titles.import') }}" enctype="multipart/form-data" style="display:flex;gap:8px;align-items:center"><input class="input" type="file" name="file" accept=".xlsx,.xls,.csv" required style="width:auto;margin-top:0">@csrf<button class="btn gray" type="submit">Import Excel</button></form>@endif @if(auth()->user()->hasPermission('job_titles.create'))<a class="btn" href="{{ route('admin.job_titles.create') }}">+ New Job Title</a>@endif @if($showHidden)<a class="btn gray" href="{{ route('admin.job_titles.index',request()->except('show_hidden')) }}">Hide Hidden</a>@else<a class="btn gray" href="{{ route('admin.job_titles.index',array_merge(request()->query(),['show_hidden'=>1])) }}">Show Hidden</a>@endif</div></div>
 <form method="get" action="{{ route('admin.job_titles.index') }}" style="display:flex;gap:8px;margin-bottom:15px;max-width:720px"><input class="input" type="search" name="search" value="{{ $search }}" placeholder="Search by code, job title, level or description" style="margin-top:0">@if($showHidden)<input type="hidden" name="show_hidden" value="1">@endif<button class="btn" type="submit">Search</button>@if($search)<a class="btn gray" href="{{ route('admin.job_titles.index',$showHidden?['show_hidden'=>1]:[]) }}">Clear</a>@endif</form>
 <div class="muted" style="margin-bottom:10px">{{ $jobTitles->total() }} job title(s)</div><div class="table-wrap"><table class="table"><thead><tr><th>Code</th><th>Job Title</th><th>Level</th><th>Target Workload Point</th><th>Users</th><th>Status</th><th>Actions</th></tr></thead><tbody>
 @forelse($jobTitles as $jt)<tr><td><strong>{{ $jt->code }}</strong></td><td>{{ $jt->name }}@if($jt->description)<div class="muted">{{ $jt->description }}</div>@endif</td><td>{{ $jt->level ?: '—' }}</td><td><strong>{{ number_format((float)$jt->target_workload_point,2) }}</strong> WP</td><td>{{ $jt->users_count }}</td><td>{{ $jt->trashed()?'Hidden':($jt->is_active?'Active':'Inactive') }}</td><td><div class="actions">@if(!$jt->trashed()) @if(auth()->user()->hasPermission('job_titles.edit'))<a class="btn gray" href="{{ route('admin.job_titles.edit',$jt) }}">Edit</a>@endif @if(auth()->user()->hasPermission('job_titles.delete'))<form method="post" action="{{ route('admin.job_titles.destroy',$jt) }}">@csrf @method('DELETE')<button class="btn red" onclick="return confirm('Hide this job title? The record will be retained.')">Hide</button></form>@endif @else @if(auth()->user()->hasPermission('job_titles.delete'))<form method="post" action="{{ route('admin.job_titles.restore',$jt->id) }}">@csrf @method('PATCH')<button class="btn" type="submit">Restore</button></form>@endif @endif</div></td></tr>@empty<tr><td colspan="7" class="muted">No job titles found.</td></tr>@endforelse
 </tbody></table></div>{{ $jobTitles->links() }}
</div>
@endsection
