@extends('layouts.admin')
@section('title','API Tester')
@section('content')
<style>
.at{max-width:1280px}.at .panel{background:#fff;border:1px solid #e1e9e4;border-radius:12px;padding:18px;box-shadow:0 2px 8px rgba(18,59,42,.05);margin-bottom:14px}.at h2,.at h3{margin:0;color:#14213d}.at .sub{margin:5px 0 14px;color:#667085;font-size:13px}.at .bar{display:grid;grid-template-columns:120px 1fr auto auto;gap:8px}.at select,.at input,.at textarea{width:100%;padding:10px;border:1px solid #cfdad3;border-radius:8px;font:inherit;box-sizing:border-box}.at select{background:#fff}.at button{padding:10px 14px;border:1px solid #c7d0da;border-radius:8px;background:#fff;color:#17365d;font-weight:650;cursor:pointer}.at button.primary{background:#17365d;border-color:#17365d;color:#fff}.at .tabs{display:flex;gap:6px;flex-wrap:wrap;margin:14px 0 8px}.at .tab{padding:7px 11px;border:1px solid #d8e0db;border-radius:8px;background:#f7f9f8;cursor:pointer;font-size:13px}.at .tab.active{background:#17365d;color:#fff;border-color:#17365d}.at .box{display:none}.at .box.active{display:block}.at .rows{display:grid;grid-template-columns:1fr 2fr auto;gap:7px;margin-bottom:7px}.at .row-actions{display:flex;gap:6px}.at .result-head{display:flex;gap:18px;align-items:center;flex-wrap:wrap}.at .status{font-size:20px;font-weight:750}.at .ok{color:#16794a}.at .bad{color:#b42318}.at .mono{font-family:ui-monospace,SFMono-Regular,monospace}.at pre{margin:0;white-space:pre-wrap;word-break:break-word;max-height:520px;overflow:auto;background:#101828;color:#e6edf3;padding:14px;border-radius:8px;font-size:12px}.at table{width:100%;border-collapse:collapse;font-size:13px}.at th,.at td{padding:8px;border:1px solid #e1e9e4;text-align:left;vertical-align:top}.at th{background:#f3f6f4}.at .hint{font-size:12px;color:#667085}.at .grid2{display:grid;grid-template-columns:1fr 1fr;gap:14px}@media(max-width:800px){.at .bar,.at .grid2{grid-template-columns:1fr}.at .rows{grid-template-columns:1fr}}
</style>
<div class="at">
<section class="panel">
<h2>API Tester</h2><p class="sub">HTTP client cho IT / DevOps: test API, authentication, headers, request body và phân tích response ngay trên hệ thống.</p>
<form id="at-form">@csrf
<div class="bar"><select id="at-method"><option>GET</option><option>POST</option><option>PUT</option><option>PATCH</option><option>DELETE</option><option>HEAD</option><option>OPTIONS</option></select><input id="at-url" required value="https://httpbin.org/get" placeholder="https://api.example.com/v1/health"><button type="button" id="at-clear">Clear</button><button class="primary" id="at-send" type="submit">▶ Send</button></div>
<div class="tabs"><button type="button" class="tab active" data-tab="params">Params</button><button type="button" class="tab" data-tab="auth">Authorization</button><button type="button" class="tab" data-tab="headers">Headers</button><button type="button" class="tab" data-tab="body">Body</button><button type="button" class="tab" data-tab="options">Options</button></div>
<div class="box active" id="box-params"><div id="param-rows"></div><button type="button" id="add-param">+ Add Param</button></div>
<div class="box" id="box-auth"><select id="auth-type"><option value="none">No Auth</option><option value="bearer">Bearer Token</option><option value="basic">Basic Auth</option><option value="apikey">API Key</option></select><div id="auth-fields" style="margin-top:8px"></div><p class="hint">Authentication chỉ được gửi tới URL bạn nhập. Không lưu token trên server.</p></div>
<div class="box" id="box-headers"><div id="header-rows"></div><button type="button" id="add-header">+ Add Header</button></div>
<div class="box" id="box-body"><select id="body-type"><option value="none">No Body</option><option value="json">JSON</option><option value="form">x-www-form-urlencoded</option><option value="raw">Raw</option></select><textarea id="at-body" rows="10" style="margin-top:8px" placeholder='{"name":"demo"}'></textarea></div>
<div class="box" id="box-options"><div class="grid2"><label>Timeout (seconds)<input id="at-timeout" type="number" min="1" max="60" value="15"></label><label style="display:flex;gap:8px;align-items:center;padding-top:26px"><input id="at-verify" type="checkbox" checked style="width:auto"> Verify SSL certificate</label><label style="display:flex;gap:8px;align-items:center"><input id="at-follow" type="checkbox" checked style="width:auto"> Follow redirects</label></div></div>
</form></section>
<div id="at-loading" class="panel" style="display:none">Đang gửi request và chờ response...</div><div id="at-result"></div>
</div>
<script>
const atToken=document.querySelector('[name=_token]').value;
const esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
function addRow(container,key='',val=''){const d=document.createElement('div');d.className='rows';d.innerHTML=`<input class="rk" placeholder="${key?'Key':''}" value="${esc(key)}"><input class="rv" placeholder="Value" value="${esc(val)}"><button type="button">×</button>`;d.querySelector('button').onclick=()=>d.remove();container.appendChild(d)}
function collect(id){const o={};document.querySelectorAll('#'+id+' .rows').forEach(r=>{const k=r.querySelector('.rk').value.trim();if(k)o[k]=r.querySelector('.rv').value});return o}
addRow(document.getElementById('param-rows'));addRow(document.getElementById('header-rows'));
document.getElementById('add-param').onclick=()=>addRow(document.getElementById('param-rows'));document.getElementById('add-header').onclick=()=>addRow(document.getElementById('header-rows'));
document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.box').forEach(x=>x.classList.remove('active'));t.classList.add('active');document.getElementById('box-'+t.dataset.tab).classList.add('active')});
function authData(){const type=document.getElementById('auth-type').value;if(type==='bearer')return {type,token:document.getElementById('auth-token')?.value||''};if(type==='basic')return {type,username:document.getElementById('auth-user')?.value||'',password:document.getElementById('auth-pass')?.value||''};if(type==='apikey')return {type,key:document.getElementById('auth-key')?.value||'',value:document.getElementById('auth-value')?.value||'',in:document.getElementById('auth-in')?.value||'header'};return {type:'none'}}
document.getElementById('auth-type').onchange=()=>{const t=document.getElementById('auth-type').value;let h='';if(t==='bearer')h='<input id="auth-token" type="password" placeholder="Bearer token">';if(t==='basic')h='<div class="grid2"><input id="auth-user" placeholder="Username"><input id="auth-pass" type="password" placeholder="Password"></div>';if(t==='apikey')h='<div class="grid2"><input id="auth-key" placeholder="Header/query key"><input id="auth-value" type="password" placeholder="API key value"></div>';document.getElementById('auth-fields').innerHTML=h};
function renderHeaders(h){return Object.entries(h||{}).map(([k,v])=>`<tr><th>${esc(k)}</th><td class="mono">${esc(v)}</td></tr>`).join('')||'<tr><td colspan="2">No response headers</td></tr>'}
document.getElementById('at-form').onsubmit=async e=>{e.preventDefault();const b=document.getElementById('at-send');b.disabled=true;document.getElementById('at-loading').style.display='block';document.getElementById('at-result').innerHTML='';const payload={method:document.getElementById('at-method').value,url:document.getElementById('at-url').value.trim(),query:collect('param-rows'),headers:collect('header-rows'),auth:authData(),body_type:document.getElementById('body-type').value,body:document.getElementById('at-body').value,timeout:parseInt(document.getElementById('at-timeout').value||15),verify_ssl:document.getElementById('at-verify').checked,follow_redirects:document.getElementById('at-follow').checked};try{const r=await fetch('{{ route('admin.it_tools.api_tester') }}',{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json','X-CSRF-TOKEN':atToken,'X-Requested-With':'XMLHttpRequest'},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw new Error(d.message||('API Tester failed (HTTP '+r.status+')'));const status=d.status?`${d.status} ${d.reason||''}`:'REQUEST ERROR';const body=d.json?JSON.stringify(d.json,null,2):(d.body||'');document.getElementById('at-result').innerHTML=`<section class="panel"><div class="result-head"><span class="status ${d.ok&&d.status<400?'ok':'bad'}">${esc(status)}</span><span>${esc(d.response_time_ms)} ms</span><span>${esc(d.response_size)} bytes</span><span class="hint">Final: ${esc(d.final_url)}</span></div>${d.error?`<p class="bad">${esc(d.error)}</p>`:''}<div class="tabs"><button type="button" class="tab active" data-r="body">Body</button><button type="button" class="tab" data-r="headers">Headers</button><button type="button" class="tab" data-r="redirects">Redirects</button><button type="button" class="tab" data-r="request">Request</button></div><div id="r-body"><pre>${esc(body)}</pre></div><div id="r-headers" style="display:none"><table>${renderHeaders(d.headers)}</table></div><div id="r-redirects" style="display:none"><pre>${esc((d.redirects||[]).join('\n')||'No redirects')}</pre></div><div id="r-request" style="display:none"><pre>${esc(JSON.stringify(d.request||{},null,2))}</pre></div></section>`;document.querySelectorAll('[data-r]').forEach(x=>x.onclick=()=>{document.querySelectorAll('[data-r]').forEach(y=>y.classList.remove('active'));['body','headers','redirects','request'].forEach(k=>document.getElementById('r-'+k).style.display='none');x.classList.add('active');document.getElementById('r-'+x.dataset.r).style.display='block'})}catch(x){document.getElementById('at-result').innerHTML=`<section class="panel"><b class="bad">ERROR</b><p>${esc(x.message)}</p></section>`}finally{b.disabled=false;document.getElementById('at-loading').style.display='none'}};
document.getElementById('at-clear').onclick=()=>{document.getElementById('at-url').value='';document.getElementById('at-body').value='';document.getElementById('param-rows').innerHTML='';document.getElementById('header-rows').innerHTML='';addRow(document.getElementById('param-rows'));addRow(document.getElementById('header-rows'));document.getElementById('at-result').innerHTML=''};
</script>
@endsection
