@extends('layouts.admin')
@section('title','IP Scanner')
@section('content')
<style>
.ips{max-width:1250px}.ips .panel{background:#fff;border:1px solid #e1e9e4;border-radius:12px;padding:18px;box-shadow:0 2px 8px rgba(18,59,42,.05);margin-bottom:14px}.ips h2,.ips h3{margin:0;color:#14213d}.ips .sub{margin:5px 0 14px;color:#667085;font-size:13px}.ips .form{display:grid;grid-template-columns:2fr 3fr auto auto;gap:10px;align-items:end}.ips label{display:block;font-weight:650;color:#344054;font-size:13px;margin-bottom:5px}.ips input{width:100%;padding:10px;border:1px solid #cfdad3;border-radius:8px;font:inherit}.ips button{padding:10px 14px;border:1px solid #c7d0da;border-radius:8px;background:#fff;color:#17365d;font-weight:650;cursor:pointer}.ips button.primary{background:#17365d;border-color:#17365d;color:#fff}.ips .portbox{display:flex;gap:8px;align-items:center;margin-top:10px;flex-wrap:wrap}.ips .portbox input[type=checkbox]{width:auto}.ips .quick{display:flex;gap:6px;flex-wrap:wrap;margin-top:8px}.ips .quick button{font-size:12px;padding:6px 9px}.ips .summary{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:14px 0}.ips .stat{border:1px solid #e1e9e4;border-radius:9px;padding:12px;background:#f8faf9}.ips .stat strong{display:block;font-size:20px;color:#17365d}.ips .stat span{font-size:12px;color:#667085}.ips .table-wrap{overflow:auto;border:1px solid #e1e9e4;border-radius:9px}.ips table{width:100%;border-collapse:collapse;font-size:13px}.ips th,.ips td{padding:9px;border:1px solid #e1e9e4;text-align:left;white-space:nowrap}.ips th{background:#f3f6f4;color:#344054}.ips .online{color:#16794a;font-weight:700}.ips .offline{color:#667085;font-weight:700}.ips .mono{font-family:ui-monospace,monospace}.ips .note{padding:10px 12px;background:#fff8e7;border:1px solid #ead89b;border-radius:8px;color:#735b00;font-size:12px}.ips .detail{background:#f8faf9;border:1px solid #e1e9e4;border-radius:8px;padding:12px;margin-top:8px;display:none}.ips .detail table{min-width:500px}.ips .loading{display:none;margin-top:10px;color:#667085;font-size:12px}@media(max-width:850px){.ips .form{grid-template-columns:1fr}.ips .summary{grid-template-columns:1fr 1fr}}
</style>
<div class="ips">
<section class="panel"><h2>IP Scanner</h2><p class="sub">Quét IP range/CIDR để xác định host đang phản hồi và các TCP service đang mở.</p><div class="note">Phạm vi tối đa 256 IPv4/scan. Custom tối đa 50 port. <b>All Ports</b> chỉ áp dụng khi scan 1 IP.</div>
<form id="ips-form" style="margin-top:14px">@csrf<div class="form"><div><label>IP Range *</label><input id="ips-range" required placeholder="192.168.1.1 - 192.168.1.254 hoặc 192.168.1.0/24"></div><div><label>Ports</label><input id="ips-ports" value="22,80,443,3389,8080,8443" placeholder="22,80,443,3389"></div><button class="primary" type="submit">▶ Scan</button><button type="button" id="ips-clear">Clear</button></div><div class="portbox"><label style="margin:0"><input id="ips-all" type="checkbox"> <b>All Ports</b> (1–65535, chỉ 1 IP)</label></div><div class="quick"><button type="button" data-ports="22,80,443">Web + SSH</button><button type="button" data-ports="80,443,8080,8443">Web Services</button><button type="button" data-ports="22,3389">Remote Access</button><button type="button" data-ports="25,465,587,993,995">Mail</button><button type="button" data-ports="3306,5432,6379,27017">Database</button></div></form><div id="ips-loading" class="loading">Đang scan, vui lòng chờ...</div></section>
<div id="ips-result"></div></div>
<script>
const ipsToken=document.querySelector('[name=_token]').value;const esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
const rangeEl=document.getElementById('ips-range'),portsEl=document.getElementById('ips-ports'),allEl=document.getElementById('ips-all');
function toggleAll(){portsEl.disabled=allEl.checked;portsEl.style.background=allEl.checked?'#f2f4f3':'#fff'} allEl.onchange=toggleAll;
document.querySelectorAll('.quick button').forEach(b=>b.onclick=()=>{allEl.checked=false;toggleAll();portsEl.value=b.dataset.ports});
document.getElementById('ips-form').onsubmit=async e=>{e.preventDefault();const all=allEl.checked;const ports=portsEl.value.split(/[,\s]+/).flatMap(v=>{if(/^\d+-\d+$/.test(v)){const [a,z]=v.split('-').map(Number);return a<=z&&z-a<50?Array.from({length:z-a+1},(_,i)=>a+i):[]}return [Number(v)]}).filter(p=>Number.isInteger(p)&&p>=1&&p<=65535);if(!all&&!ports.length){alert('Nhập ít nhất 1 port.');return}const btn=e.submitter,loading=document.getElementById('ips-loading');btn.disabled=true;loading.style.display='block';try{const r=await fetch('{{ route('admin.it_tools.ip_scanner') }}',{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json','X-CSRF-TOKEN':ipsToken,'X-Requested-With':'XMLHttpRequest'},body:JSON.stringify({range:rangeEl.value.trim(),ports:[...new Set(ports)].slice(0,50),all_ports:all})});const d=await r.json();if(!r.ok)throw new Error(d.message||('IP scan failed (HTTP '+r.status+')'));const rows=d.results.map((x,i)=>`<tr><td class="mono">${esc(x.ip)}</td><td class="${x.status==='online'?'online':'offline'}">${esc(x.status.toUpperCase())}</td><td>${x.response_time_ms===null?'—':esc(x.response_time_ms)+' ms'}</td><td class="mono">${esc(x.hostname||'—')}</td><td>${x.open_ports.length?x.open_ports.map(p=>`<span class="mono">${p.port}</span> ${esc(p.service)}`).join('<br>'):'—'}</td><td>${x.open_port_count}</td><td><button type="button" onclick="showIpDetail(${i})">Detail</button></td></tr>`).join('');window.ipRows=d.results;document.getElementById('ips-result').innerHTML=`<section class="panel"><h3>Scan Result</h3><p class="sub">Range: <span class="mono">${esc(d.range)}</span> · Scanned: ${d.total} · ${esc(d.scanned_at)}</p><div class="summary"><div class="stat"><strong>${d.total}</strong><span>TOTAL IP</span></div><div class="stat"><strong>${d.online}</strong><span>ONLINE</span></div><div class="stat"><strong>${d.offline}</strong><span>OFFLINE</span></div><div class="stat"><strong>${all?'1–65535':'Custom'}</strong><span>PORT PROFILE</span></div></div><div class="table-wrap"><table><thead><tr><th>IP</th><th>Status</th><th>Latency</th><th>PTR / Hostname</th><th>Open Ports</th><th>Count</th><th></th></tr></thead><tbody>${rows}</tbody></table></div><div id="ips-detail" class="detail"></div></section>`}catch(x){document.getElementById('ips-result').innerHTML=`<section class="panel"><b style="color:#b42318">ERROR</b><p>${esc(x.message)}</p></section>`}finally{btn.disabled=false;loading.style.display='none'}};
window.showIpDetail=i=>{const x=window.ipRows[i],el=document.getElementById('ips-detail');el.style.display='block';el.innerHTML=`<b>${esc(x.ip)} — Detail</b><table style="margin-top:8px"><tr><th>IP</th><td class="mono">${esc(x.ip)}</td></tr><tr><th>Status</th><td>${esc(x.status)}</td></tr><tr><th>Latency</th><td>${x.response_time_ms===null?'—':esc(x.response_time_ms)+' ms'}</td></tr><tr><th>PTR</th><td class="mono">${esc(x.ptr||'Not found')}</td></tr><tr><th>Checked Ports</th><td>${x.checked_ports}</td></tr><tr><th>Open Ports</th><td>${x.open_ports.length?x.open_ports.map(p=>esc(p.port)+' — '+esc(p.service)).join('<br>'):'None detected'}</td></tr></table>`};
document.getElementById('ips-clear').onclick=()=>{rangeEl.value='';portsEl.value='22,80,443,3389,8080,8443';allEl.checked=false;toggleAll();document.getElementById('ips-result').innerHTML=''};
</script>
@endsection
