@extends('layouts.admin')
@section('title','Network Diagnostic')
@section('content')
<style>
.nd{max-width:1180px}.nd .panel{background:#fff;border:1px solid #e1e9e4;border-radius:12px;padding:18px;box-shadow:0 2px 8px rgba(18,59,42,.05);margin-bottom:14px}.nd h2,.nd h3{margin:0;color:#14213d}.nd .sub{margin:5px 0 14px;color:#667085;font-size:13px}.nd .tabs{display:flex;gap:6px;margin-bottom:14px}.nd .tab{padding:9px 14px;border:1px solid #cfdad3;border-radius:8px;background:#fff;cursor:pointer;font-weight:650;color:#344054}.nd .tab.active{background:#17365d;color:#fff;border-color:#17365d}.nd .form{display:grid;grid-template-columns:3fr 1fr auto;gap:10px;align-items:end}.nd label{display:block;font-weight:650;color:#344054;font-size:13px;margin-bottom:5px}.nd input{width:100%;padding:10px;border:1px solid #cfdad3;border-radius:8px;font:inherit}.nd button{padding:10px 14px;border:1px solid #c7d0da;border-radius:8px;background:#fff;color:#17365d;font-weight:650;cursor:pointer}.nd button.primary{background:#17365d;border-color:#17365d;color:#fff}.nd .summary{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:14px 0}.nd .stat{border:1px solid #e1e9e4;border-radius:9px;padding:12px;background:#f8faf9}.nd .stat strong{display:block;font-size:20px;color:#17365d}.nd .stat span{font-size:12px;color:#667085}.nd .table-wrap{overflow:auto;border:1px solid #e1e9e4;border-radius:9px}.nd table{width:100%;border-collapse:collapse;font-size:13px}.nd th,.nd td{padding:9px;border:1px solid #e1e9e4;text-align:left}.nd th{background:#f3f6f4;color:#344054}.nd .mono{font-family:ui-monospace,monospace}.nd pre{white-space:pre-wrap;word-break:break-word;background:#101828;color:#e6edf3;border-radius:9px;padding:14px;overflow:auto;max-height:560px}.nd .loading{display:none;margin-top:10px;color:#667085;font-size:12px}@media(max-width:800px){.nd .form{grid-template-columns:1fr}.nd .summary{grid-template-columns:1fr 1fr}}
</style>
<div class="nd"><section class="panel"><h2>Network Diagnostic</h2><p class="sub">Ping và Traceroute/Tracepath dùng chung một màn hình để troubleshooting đường truyền tới Host/IP.</p><div class="tabs"><button type="button" class="tab active" data-mode="ping">Ping IP / Host</button><button type="button" class="tab" data-mode="trace">Traceroute Route</button></div><form id="nd-form">@csrf<div class="form"><div><label>IP / Host *</label><input id="nd-host" required value="8.8.8.8" placeholder="8.8.8.8 hoặc example.com"></div><div id="nd-count-wrap"><label>Ping Count</label><input id="nd-count" type="number" min="1" max="10" value="4"></div><button class="primary" type="submit">▶ Run</button></div></form><div id="nd-loading" class="loading">Đang kiểm tra...</div></section><div id="nd-result"></div></div>
<script>
const ndToken=document.querySelector('[name=_token]').value;let ndMode='ping';const esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{ndMode=t.dataset.mode;document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===t));document.getElementById('nd-count-wrap').innerHTML=ndMode==='ping'?'<label>Ping Count</label><input id="nd-count" type="number" min="1" max="10" value="4">':'<label>Max Hops</label><input id="nd-count" type="number" min="1" max="64" value="30">'});
document.getElementById('nd-form').onsubmit=async e=>{e.preventDefault();const btn=e.submitter,load=document.getElementById('nd-loading'),host=document.getElementById('nd-host').value.trim(),value=Math.max(1,Math.min(parseInt(document.getElementById('nd-count').value||'4',10),ndMode==='ping'?10:64));btn.disabled=true;load.style.display='block';try{const r=await fetch('{{ route('admin.it_tools.network_diagnostic') }}',{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json','X-CSRF-TOKEN':ndToken,'X-Requested-With':'XMLHttpRequest'},body:JSON.stringify({mode:ndMode,host,count:value})});const d=await r.json();if(!r.ok)throw new Error(d.message||('Diagnostic failed (HTTP '+r.status+')'));if(ndMode==='ping'){const s=d.summary||{};document.getElementById('nd-result').innerHTML=`<section class="panel"><h3>Ping Result</h3><p class="sub">Target: <span class="mono">${esc(d.host)}</span> · ${esc(d.checked_at)}</p><div class="summary"><div class="stat"><strong>${s.received??0}/${s.transmitted??d.count}</strong><span>REPLIES</span></div><div class="stat"><strong>${s.packet_loss_percent??'—'}%</strong><span>PACKET LOSS</span></div><div class="stat"><strong>${s.avg_ms??'—'} ms</strong><span>AVERAGE</span></div><div class="stat"><strong>${s.max_ms??'—'} ms</strong><span>MAX</span></div></div><pre>${esc(d.output)}</pre></section>`}else{const rows=(d.hops||[]).map(h=>`<tr><td>${h.hop}</td><td class="mono">${h.addresses?.length?h.addresses.map(esc).join('<br>'):'*'}</td><td>${h.latencies_ms?.length?h.latencies_ms.map(x=>esc(x)+' ms').join('<br>'):'*'}</td><td>${esc(h.raw)}</td></tr>`).join('');document.getElementById('nd-result').innerHTML=`<section class="panel"><h3>Traceroute Result</h3><p class="sub">Target: <span class="mono">${esc(d.host)}</span> · Max hops: ${d.max_hops} · ${esc(d.checked_at)}</p><div class="table-wrap"><table><thead><tr><th>Hop</th><th>Address</th><th>Latency</th><th>Raw</th></tr></thead><tbody>${rows||'<tr><td colspan="4">No hop data returned.</td></tr>'}</tbody></table></div><pre style="margin-top:12px">${esc(d.output)}</pre></section>`}}catch(x){document.getElementById('nd-result').innerHTML=`<section class="panel"><b style="color:#b42318">ERROR</b><p>${esc(x.message)}</p></section>`}finally{btn.disabled=false;load.style.display='none'}};
</script>
@endsection
