@extends('layouts.admin')
@section('title','Port Check')
@section('content')
<style>
.pc{max-width:1180px}.pc .panel{background:#fff;border:1px solid #e1e9e4;border-radius:12px;padding:18px;box-shadow:0 2px 8px rgba(18,59,42,.05);margin-bottom:14px}.pc h2,.pc h3{margin:0;color:#14213d}.pc .sub{margin:5px 0 14px;color:#667085;font-size:13px}.pc .form{display:grid;grid-template-columns:2fr 2fr auto auto;gap:10px;align-items:end}.pc label{display:block;font-weight:650;color:#344054;font-size:13px;margin-bottom:5px}.pc input,.pc select{width:100%;padding:10px;border:1px solid #cfdad3;border-radius:8px;font:inherit;box-sizing:border-box}.pc button{padding:10px 14px;border:1px solid #c7d0da;border-radius:8px;background:#fff;color:#17365d;font-weight:650;cursor:pointer}.pc button.primary{background:#17365d;border-color:#17365d;color:#fff}.pc button:disabled{opacity:.55;cursor:not-allowed}.pc .ports{display:flex;gap:6px;flex-wrap:wrap}.pc .port{padding:5px 9px;border:1px solid #d8e0db;border-radius:999px;background:#f7f9f8;cursor:pointer;font-size:12px}.pc .port input{width:auto;margin-right:4px}.pc .summary{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:14px 0}.pc .stat{border:1px solid #e1e9e4;border-radius:9px;padding:12px;background:#f8faf9}.pc .stat strong{display:block;font-size:20px;color:#17365d}.pc .stat span{font-size:12px;color:#667085}.pc .table-wrap{overflow:auto;border:1px solid #e1e9e4;border-radius:9px}.pc table{width:100%;border-collapse:collapse;font-size:13px}.pc th,.pc td{padding:9px;border:1px solid #e1e9e4;text-align:left}.pc th{background:#f3f6f4;color:#344054}.pc .open{color:#16794a;font-weight:700}.pc .closed{color:#667085;font-weight:700}.pc .timeout,.pc .error,.pc .filtered\/timeout,.pc .unreachable\/error{color:#b42318;font-weight:700}.pc .mono{font-family:ui-monospace,monospace}.pc .note{padding:10px 12px;background:#fff8e7;border:1px solid #ead89b;border-radius:8px;color:#735b00;font-size:12px}.pc .progress{margin-top:14px;display:none}.pc .progress-head{display:flex;justify-content:space-between;gap:8px;margin-bottom:7px;font-size:12px;color:#667085}.pc .bar{height:9px;background:#e8eeea;border-radius:999px;overflow:hidden}.pc .bar>span{display:block;height:100%;width:0;background:#17365d;transition:width .15s ease}.pc .process{margin-top:12px;max-height:280px;overflow:auto;border:1px solid #e1e9e4;border-radius:9px}.pc .process-row{display:grid;grid-template-columns:70px 1fr 120px 95px;gap:8px;padding:8px 10px;border-bottom:1px solid #eef2ef;font-size:12px;align-items:center}.pc .process-row:last-child{border-bottom:0}.pc .badge{display:inline-block;padding:3px 7px;border-radius:999px;background:#f2f4f7;color:#344054;font-weight:700}.pc .badge.open{background:#e8f6ee}.pc .badge.closed{background:#f2f4f7}.pc .badge.filtered\/timeout,.pc .badge.unreachable\/error{background:#fff0ee}.pc .running{font-weight:700;color:#17365d}@media(max-width:800px){.pc .form{grid-template-columns:1fr}.pc .summary{grid-template-columns:1fr 1fr}.pc .process-row{grid-template-columns:60px 1fr 100px}}
</style>
<div class="pc">
<section class="panel"><h2>Port Check</h2><p class="sub">Kiểm tra kết nối TCP tới một Host / IP. Có thể kiểm tra các port chỉ định hoặc toàn bộ 1–65535.</p><div class="note">All Ports chỉ áp dụng cho <strong>một Host / IP</strong>. Khi chọn All Ports, hệ thống kiểm tra lần lượt các TCP port từ 1 đến 65535 và hiển thị tiến trình từng port.</div><form id="pc-form" style="margin-top:14px">@csrf<div class="form"><div><label>Host / IP *</label><input id="pc-host" required placeholder="example.com hoặc 1.2.3.4"></div><div><label>Ports</label><input id="pc-ports" value="22,25,53,80,443,3306,3389,5432,6379,8080" placeholder="22,80,443,3306"></div><button class="primary" type="submit">▶ Check Ports</button><button type="button" id="pc-clear">Clear</button></div><div class="ports" style="margin-top:10px"><label class="port"><input type="checkbox" id="pc-all-ports"> Scan All Ports (1–65535)</label>@foreach([22=>'SSH',25=>'SMTP',53=>'DNS',80=>'HTTP',443=>'HTTPS',445=>'SMB',587=>'SMTP Submission',993=>'IMAPS',3306=>'MySQL',3389=>'RDP',5432=>'PostgreSQL',6379=>'Redis',8080=>'HTTP-Alt',8443=>'HTTPS-Alt',27017=>'MongoDB'] as $port=>$name)<label class="port"><input type="checkbox" class="pc-preset" value="{{ $port }}">{{ $port }} {{ $name }}</label>@endforeach</div></form><div class="progress" id="pc-progress"><div class="progress-head"><span id="pc-progress-label">Preparing...</span><span id="pc-progress-count">0 / 0</span></div><div class="bar"><span id="pc-progress-bar"></span></div><div class="process" id="pc-process"></div></div></section>
<div id="pc-result"></div></div>
<script>
const pcToken=document.querySelector('[name=_token]').value;const esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
const hostEl=document.getElementById('pc-host'), portsEl=document.getElementById('pc-ports'), allEl=document.getElementById('pc-all-ports'), formEl=document.getElementById('pc-form');
const progressEl=document.getElementById('pc-progress'), progressLabel=document.getElementById('pc-progress-label'), progressCount=document.getElementById('pc-progress-count'), progressBar=document.getElementById('pc-progress-bar'), processEl=document.getElementById('pc-process');
const presetEls=[...document.querySelectorAll('.pc-preset')];
function selectedPorts(){const manual=portsEl.value.split(',').map(x=>parseInt(x.trim(),10)).filter(x=>Number.isInteger(x)&&x>=1&&x<=65535);const checked=presetEls.filter(x=>x.checked).map(x=>parseInt(x.value,10));return [...new Set([...manual,...checked])].slice(0,30)}
function syncAll(){const all=allEl.checked;portsEl.disabled=all;presetEls.forEach(x=>x.disabled=all);}
presetEls.forEach(x=>x.onchange=()=>{if(!allEl.checked){portsEl.value=selectedPorts().join(',')}}); allEl.onchange=syncAll; syncAll();
function statusLabel(s){return String(s||'').replaceAll('filtered/timeout','TIMEOUT').replaceAll('unreachable/error','ERROR').toUpperCase()}
function addProcessRow(port,status,service,ms){const row=document.createElement('div');row.className='process-row';row.innerHTML=`<span class="mono">${esc(port)}</span><span>${esc(service||'TCP')}</span><span class="badge ${esc(status)}">${esc(statusLabel(status))}</span><span>${ms==null?'—':esc(ms)+' ms'}</span>`;processEl.appendChild(row);processEl.scrollTop=processEl.scrollHeight;}
function updateProgress(done,total,text){const pct=total?Math.round(done/total*100):0;progressLabel.textContent=text||'Checking...';progressCount.textContent=`${done.toLocaleString()} / ${total.toLocaleString()}`;progressBar.style.width=pct+'%'}
async function checkOne(host,port){const r=await fetch('{{ route('admin.it_tools.port_check') }}',{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json','X-CSRF-TOKEN':pcToken,'X-Requested-With':'XMLHttpRequest'},body:JSON.stringify({host,ports:[port]})});const d=await r.json();if(!r.ok)throw new Error(d.message||('Port check failed (HTTP '+r.status+')'));return d.ports?.[0]||{port,status:'unreachable/error',service:'TCP',response_time_ms:null,error:d.message||null}}
async function runScan(e){e.preventDefault();const host=hostEl.value.trim();if(!host)return;const all=allEl.checked;const ports=all?Array.from({length:65535},(_,i)=>i+1):selectedPorts();if(!ports.length){alert('Nhập ít nhất 1 port.');return}
 const button=formEl.querySelector('button.primary');button.disabled=true;progressEl.style.display='block';processEl.innerHTML='';document.getElementById('pc-result').innerHTML='';updateProgress(0,ports.length,all?'Scanning all TCP ports...':'Checking selected ports...');const results=[];try{for(let i=0;i<ports.length;i++){const port=ports[i];updateProgress(i,ports.length,all?`Checking TCP port ${port}...`:`Checking port ${port}...`);let item;try{item=await checkOne(host,port)}catch(err){item={port,status:'unreachable/error',service:'TCP',response_time_ms:null,error:err.message}}results.push(item);addProcessRow(item.port,item.status,item.service,item.response_time_ms);updateProgress(i+1,ports.length,all?`Checked TCP port ${port}`:`Checked port ${port}`)}
 const open=results.filter(x=>x.status==='open').length,closed=results.filter(x=>x.status==='closed').length,other=results.length-open-closed;document.getElementById('pc-result').innerHTML=`<section class="panel"><h3>Port Check Result</h3><p class="sub">Target: <span class="mono">${esc(host)}</span> · ${all?'All Ports (1–65535)':'Selected Ports'} · Checked ${new Date().toLocaleString()}</p><div class="summary"><div class="stat"><strong>${open}</strong><span>OPEN</span></div><div class="stat"><strong>${closed}</strong><span>CLOSED</span></div><div class="stat"><strong>${other}</strong><span>TIMEOUT / ERROR</span></div><div class="stat"><strong>${results.length}</strong><span>CHECKED</span></div></div><div class="table-wrap"><table><thead><tr><th>Port</th><th>Service</th><th>Status</th><th>Response</th><th>Error</th></tr></thead><tbody>${results.map(x=>`<tr><td class="mono">${x.port}</td><td>${esc(x.service)}</td><td class="${esc(x.status)}">${esc(statusLabel(x.status))}</td><td>${x.response_time_ms==null?'—':esc(x.response_time_ms)+' ms'}</td><td>${esc(x.error||'—')}</td></tr>`).join('')}</tbody></table></div></section>`;
 }catch(err){document.getElementById('pc-result').innerHTML=`<section class="panel"><b style="color:#b42318">ERROR</b><p>${esc(err.message)}</p></section>`}finally{button.disabled=false;}}
formEl.onsubmit=runScan;
document.getElementById('pc-clear').onclick=()=>{hostEl.value='';portsEl.value='22,25,53,80,443,3306,3389,5432,6379,8080';allEl.checked=false;portsEl.disabled=false;presetEls.forEach(x=>{x.checked=false;x.disabled=false});progressEl.style.display='none';processEl.innerHTML='';document.getElementById('pc-result').innerHTML='';updateProgress(0,0,'Preparing...')};
</script>
@endsection
