@extends('layouts.admin')
@section('title','Port Check')
@section('content')
<style>
.pc{max-width:1180px}.pc .panel{background:#fff;border:1px solid #e1e9e4;border-radius:12px;padding:18px;box-shadow:0 2px 8px rgba(18,59,42,.05);margin-bottom:14px}.pc h2,.pc h3{margin:0;color:#14213d}.pc .sub{margin:5px 0 14px;color:#667085;font-size:13px}.pc .form{display:grid;grid-template-columns:2fr 2fr auto auto;gap:10px;align-items:end}.pc label{display:block;font-weight:650;color:#344054;font-size:13px;margin-bottom:5px}.pc input{width:100%;padding:10px;border:1px solid #cfdad3;border-radius:8px;font:inherit}.pc button{padding:10px 14px;border:1px solid #c7d0da;border-radius:8px;background:#fff;color:#17365d;font-weight:650;cursor:pointer}.pc button.primary{background:#17365d;border-color:#17365d;color:#fff}.pc .ports{display:flex;gap:6px;flex-wrap:wrap}.pc .port{padding:5px 9px;border:1px solid #d8e0db;border-radius:999px;background:#f7f9f8;cursor:pointer;font-size:12px}.pc .port input{width:auto;margin-right:4px}.pc .actions{display:flex;gap:8px;margin-top:12px}.pc .summary{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:14px 0}.pc .stat{border:1px solid #e1e9e4;border-radius:9px;padding:12px;background:#f8faf9}.pc .stat strong{display:block;font-size:20px;color:#17365d}.pc .stat span{font-size:12px;color:#667085}.pc .table-wrap{overflow:auto;border:1px solid #e1e9e4;border-radius:9px}.pc table{width:100%;border-collapse:collapse;font-size:13px}.pc th,.pc td{padding:9px;border:1px solid #e1e9e4;text-align:left}.pc th{background:#f3f6f4;color:#344054}.pc .open{color:#16794a;font-weight:700}.pc .closed{color:#667085;font-weight:700}.pc .timeout,.pc .error{color:#b42318;font-weight:700}.pc .mono{font-family:ui-monospace,monospace}.pc .note{padding:10px 12px;background:#fff8e7;border:1px solid #ead89b;border-radius:8px;color:#735b00;font-size:12px}@media(max-width:800px){.pc .form{grid-template-columns:1fr}.pc .summary{grid-template-columns:1fr 1fr}}
</style>
<div class="pc">
<section class="panel"><h2>Port Check</h2><p class="sub">Kiểm tra kết nối TCP tới các port được chỉ định. Dùng cho troubleshooting Server / Firewall / Service.</p><div class="note">Chỉ kiểm tra các port do người dùng chỉ định, tối đa 30 port/lần. Không quét port range hoặc tự động discovery.</div><form id="pc-form" style="margin-top:14px">@csrf<div class="form"><div><label>Host / IP *</label><input id="pc-host" required placeholder="example.com hoặc 1.2.3.4"></div><div><label>Ports</label><input id="pc-ports" value="22,25,53,80,443,3306,3389,5432,6379,8080" placeholder="22,80,443,3306"></div><button class="primary" type="submit">▶ Check Ports</button><button type="button" id="pc-clear">Clear</button></div><div class="ports" style="margin-top:10px">@foreach([22=>'SSH',25=>'SMTP',53=>'DNS',80=>'HTTP',443=>'HTTPS',445=>'SMB',587=>'SMTP Submission',993=>'IMAPS',3306=>'MySQL',3389=>'RDP',5432=>'PostgreSQL',6379=>'Redis',8080=>'HTTP-Alt',8443=>'HTTPS-Alt',27017=>'MongoDB'] as $port=>$name)<label class="port"><input type="checkbox" value="{{ $port }}">{{ $port }} {{ $name }}</label>@endforeach</div></form><div id="pc-loading" style="display:none;margin-top:10px;color:#667085;font-size:12px">Đang kiểm tra...</div></section>
<div id="pc-result"></div></div>
<script>
const pcToken=document.querySelector('[name=_token]').value;const esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
function selectedPorts(){const manual=document.getElementById('pc-ports').value.split(',').map(x=>parseInt(x.trim(),10)).filter(x=>Number.isInteger(x)&&x>=1&&x<=65535);const checked=[...document.querySelectorAll('.ports input:checked')].map(x=>parseInt(x.value,10));return [...new Set([...manual,...checked])].slice(0,30)}
document.querySelectorAll('.ports input').forEach(x=>x.onchange=()=>{const p=selectedPorts();document.getElementById('pc-ports').value=p.join(',')});
document.getElementById('pc-form').onsubmit=async e=>{e.preventDefault();const ports=selectedPorts();if(!ports.length){alert('Nhập ít nhất 1 port.');return}const b=document.querySelector('#pc-form button.primary'),l=document.getElementById('pc-loading');b.disabled=true;l.style.display='block';try{const r=await fetch('{{ route('admin.it_tools.port_check') }}',{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json','X-CSRF-TOKEN':pcToken,'X-Requested-With':'XMLHttpRequest'},body:JSON.stringify({host:document.getElementById('pc-host').value.trim(),ports})});const d=await r.json();if(!r.ok)throw new Error(d.message||('Port check failed (HTTP '+r.status+')'));const open=d.ports.filter(x=>x.status==='open').length,closed=d.ports.filter(x=>x.status==='closed').length,other=d.ports.length-open-closed;document.getElementById('pc-result').innerHTML=`<section class="panel"><h3>Port Check Result</h3><p class="sub">Target: <span class="mono">${esc(d.host)}</span> → <span class="mono">${esc(d.target)}</span> · ${esc(d.family||'Unknown')} · Checked ${esc(d.checked_at)}</p><div class="summary"><div class="stat"><strong>${open}</strong><span>OPEN</span></div><div class="stat"><strong>${closed}</strong><span>CLOSED</span></div><div class="stat"><strong>${other}</strong><span>TIMEOUT / ERROR</span></div><div class="stat"><strong>${d.ports.length}</strong><span>CHECKED</span></div></div><div class="table-wrap"><table><thead><tr><th>Port</th><th>Service</th><th>Status</th><th>Response</th><th>Error</th></tr></thead><tbody>${d.ports.map(x=>`<tr><td class="mono">${x.port}</td><td>${esc(x.service)}</td><td class="${esc(x.status)}">${esc(x.status.toUpperCase())}</td><td>${esc(x.response_time_ms)} ms</td><td>${esc(x.error||'—')}</td></tr>`).join('')}</tbody></table></div><p class="sub" style="margin-top:12px">PTR: <span class="mono">${esc(d.ptr||'Not found')}</span></p></section>`}catch(x){document.getElementById('pc-result').innerHTML=`<section class="panel"><b style="color:#b42318">ERROR</b><p>${esc(x.message)}</p></section>`}finally{b.disabled=false;l.style.display='none'}};
document.getElementById('pc-clear').onclick=()=>{document.getElementById('pc-host').value='';document.getElementById('pc-ports').value='22,25,53,80,443,3306,3389,5432,6379,8080';document.querySelectorAll('.ports input').forEach(x=>x.checked=false);document.getElementById('pc-result').innerHTML=''};
</script>
@endsection
