@extends('layouts.admin')
@section('title','IT Outsourcing Tools')
@section('content')
<style>
.itw{--ink:#14213d;--muted:#667085;--line:#e4e7ec;--soft:#f7f9fc;--brand:#17365d;--green:#16794a;--amber:#9a6700;--red:#b42318;font-size:14px}
.itw *{box-sizing:border-box}.itw .hero{background:linear-gradient(135deg,#f7fbff,#fff);border:1px solid #dfe7ef;border-radius:16px;padding:24px;box-shadow:0 8px 28px rgba(16,40,64,.06)}
.itw .hero h2{margin:0;color:var(--ink);font-size:25px}.itw .hero p{margin:6px 0 0;color:var(--muted)}
.itw .grid{display:grid;grid-template-columns:repeat(12,1fr);gap:14px;margin-top:20px}.itw .panel{background:#fff;border:1px solid var(--line);border-radius:14px;padding:18px;box-shadow:0 3px 14px rgba(16,24,40,.04)}
.itw .single{grid-column:span 8}.itw .quick{grid-column:span 4}.itw .bulk{grid-column:1/-1}.itw h3{margin:0;color:var(--ink);font-size:17px}.itw .sub{margin:4px 0 16px;color:var(--muted);font-size:13px}
.itw .formgrid{display:grid;grid-template-columns:2fr 1.2fr 1.8fr auto;gap:12px;align-items:end}.itw label{display:block;font-weight:650;color:#344054;margin-bottom:6px;font-size:13px}.itw input,.itw textarea,.itw select{width:100%;border:1px solid #cfd6df;border-radius:9px;padding:10px 11px;background:#fff;color:#172b4d;font:inherit;outline:none}.itw input:focus,.itw textarea:focus{border-color:#6b8fb3;box-shadow:0 0 0 3px rgba(52,101,148,.1)}
.itw button,.itw .btn{border:1px solid #c7d0da;border-radius:9px;padding:10px 13px;background:#fff;color:#17365d;font-weight:650;text-decoration:none;cursor:pointer;display:inline-flex;align-items:center;justify-content:center;gap:7px}.itw button.primary,.itw .btn.primary{background:#17365d;border-color:#17365d;color:#fff}.itw button:hover,.itw .btn:hover{filter:brightness(.98)}
.itw .advanced{margin-top:14px;border:1px solid var(--line);border-radius:10px;background:var(--soft);padding:0 13px}.itw .advanced summary{cursor:pointer;padding:11px 0;font-weight:650;color:#344054}.itw .advanced-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px;padding:2px 0 14px}.itw .hint{font-size:11.5px;color:var(--muted);margin-top:5px}.itw .actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:14px}
.itw .quick-list{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:12px}.itw .quick-item{border:1px solid var(--line);background:var(--soft);border-radius:10px;padding:10px}.itw .quick-item strong{display:block;color:var(--ink);font-size:13px}.itw .quick-item span{font-size:11px;color:var(--muted)}
.itw .bulk-grid{display:block}.itw textarea{min-height:130px;resize:vertical;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:12.5px}.itw .statusbar{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}.itw .pill{border:1px solid var(--line);background:#fff;border-radius:999px;padding:5px 9px;font-size:12px;color:#475467}.itw .pill strong{color:var(--ink)}
.itw .result-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start;flex-wrap:wrap}.itw .score{display:inline-flex;align-items:center;border-radius:999px;padding:6px 11px;font-weight:700;font-size:12px}.itw .ok{background:#ecfdf3;color:var(--green)}.itw .warn{background:#fffaeb;color:var(--amber)}.itw .bad{background:#fef3f2;color:var(--red)}
.itw .cards{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-top:14px}.itw .audit-card{border:1px solid var(--line);border-radius:12px;padding:14px;background:#fff}.itw .audit-card h4{margin:0 0 10px;color:var(--ink);font-size:14px}.itw .kv{display:grid;grid-template-columns:110px 1fr;gap:6px 10px;font-size:12px}.itw .kv b{color:#667085;font-weight:600}.itw .kv span{color:#1d2939;word-break:break-word}.itw .mono{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:11.5px}
.itw details.section{margin-top:12px;border:1px solid var(--line);border-radius:12px;background:#fff}.itw details.section summary{cursor:pointer;padding:13px 15px;font-weight:700;color:var(--ink)}.itw .section-body{padding:0 15px 15px}.itw .records{width:100%;border-collapse:collapse;font-size:12px}.itw .records th,.itw .records td{border:1px solid var(--line);padding:7px 8px;text-align:left;vertical-align:top}.itw .records th{background:#f5f7fa;color:#344054}.itw .records td{word-break:break-word}.itw .service-table{max-height:420px;overflow:auto}.itw .service-table .records th{position:sticky;top:0;z-index:1}
.itw .bulk-table-wrap{overflow:auto;border:1px solid var(--line);border-radius:12px;margin-top:14px}.itw .bulk-table{width:max-content;min-width:100%;border-collapse:separate;border-spacing:0;font-size:11.5px}.itw .bulk-table th,.itw .bulk-table td{padding:7px 9px;border-right:1px solid var(--line);border-bottom:1px solid var(--line);vertical-align:top;white-space:nowrap}.itw .bulk-table thead th{background:#f3f6f8;color:#172b4d;font-weight:700;position:sticky;top:0;z-index:3}.itw .bulk-table td.wrap{white-space:normal;min-width:180px;max-width:320px;word-break:break-word}.itw .bulk-table tbody tr:nth-child(even) td{background:#fbfcfd}.itw .bulk-table tbody tr:hover td{background:#f0f7ff}.itw .bulk-table .group th{background:#17365d;color:#fff;text-align:center}.itw .bulk-table .group .web{background:#3c6e71}.itw .bulk-table .group .ssl{background:#6c5b7b}.itw .bulk-table .group .ip{background:#7b5e57}.itw .bulk-table .group .dns{background:#4f6d4f}.itw .bulk-table .group .mail{background:#8a6d3b}.itw .bulk-table .group .provider{background:#52616b}.itw .bulk-table .group .error{background:#7f1d1d}
.itw .notice{padding:10px 12px;border-radius:9px;background:#f8fafc;border:1px solid var(--line);color:#475467;font-size:12px}.itw .loading{display:none;margin-top:12px;color:#667085;font-size:12px}.itw .spin{display:inline-block;width:13px;height:13px;border:2px solid #cbd5e1;border-top-color:#17365d;border-radius:50%;animation:sp .7s linear infinite;vertical-align:-2px}@keyframes sp{to{transform:rotate(360deg)}}
@media(max-width:1100px){.itw .single,.itw .quick{grid-column:1/-1}.itw .formgrid{grid-template-columns:1fr 1fr}.itw .cards{grid-template-columns:1fr 1fr}}@media(max-width:700px){.itw .formgrid,.itw .advanced-grid,.itw .bulk-grid,.itw .cards{grid-template-columns:1fr}.itw .hero{padding:18px}}
</style>
<div class="itw">
  <div class="hero"><h2>IT Outsourcing Tools</h2><p>Unified Internet Asset Audit for Domain, DNS, SSL/TLS, Website, Email, IP/Hosting and Service Discovery.</p></div>
  <div class="grid">
    <section class="panel single">
      <h3>Single Domain Audit</h3><p class="sub">Một lần kiểm tra sẽ chạy toàn bộ các module backend hiện có.</p>
      <form id="audit-form">@csrf
        <div class="formgrid">
          <div><label for="domain">Domain <span style="color:#b42318">*</span></label><input id="domain" required placeholder="example.com hoặc example.vn"></div>
          <div><label for="wan_ip">WAN / Origin IP</label><input id="wan_ip" placeholder="1.2.3.4"></div>
          <button class="primary" type="submit">▶ Run Audit</button><button type="button" id="clear-single">Clear</button>
        </div>
        <details class="advanced"><summary>Advanced Options — Email & Service Discovery</summary><div class="advanced-grid">
          <div><label for="dkim_selectors">DKIM Selectors</label><input id="dkim_selectors" placeholder="selector1, selector2"><div class="hint">Nhập selector thực tế để kiểm tra selector._domainkey.domain.</div></div>
          <div><label for="service_hosts">Service Hosts</label><input id="service_hosts" placeholder="vpn, mail, portal hoặc vpn.company.vn"><div class="hint">Bỏ trống = kiểm tra 18 hostname mặc định; tối đa 50 host.</div></div>
        </div></details>
        <div class="actions"><a class="btn" href="{{ route('admin.it_tools.history') }}">◷ Audit History</a><a class="btn" href="{{ route('admin.it_tools.history.export') }}">⇩ Export Excel</a></div>
      </form>
      <div id="single-loading" class="loading"><span class="spin"></span> Đang thực hiện Domain + DNS + SSL/TLS + Website + Email + IP + Service Discovery...</div>
    </section>
    <aside class="panel quick"><h3>Audit Coverage</h3><p class="sub">Các capability backend đang được sử dụng trực tiếp.</p><div class="quick-list">
      <div class="quick-item"><strong>🌐 Domain</strong><span>Expiry · Registrar · Status · Source</span></div><div class="quick-item"><strong>🧭 DNS</strong><span>All public RR types · DNSSEC · Provider</span></div>
      <div class="quick-item"><strong>🔐 SSL / TLS</strong><span>CA · SAN · TLS · Cipher · Hostname</span></div><div class="quick-item"><strong>🖥 Website</strong><span>HTTP/HTTPS · Status · Redirect · Headers</span></div>
      <div class="quick-item"><strong>✉ Email</strong><span>MX · SPF · DMARC · DKIM · MTA-STS · TLS-RPT</span></div><div class="quick-item"><strong>☁ Infrastructure</strong><span>IP · ASN · Network · CDN · WAF · Hosting</span></div>
      <div class="quick-item"><strong>🔎 Services</strong><span>18 default hosts or custom hosts</span></div><div class="quick-item"><strong>📊 Operations</strong><span>History · Bulk · Excel</span></div>
    </div></aside>
    <section class="panel bulk"><h3>Bulk Audit</h3><p class="sub">Tối đa 100 domain/lần. Có thể nhập Domain + WAN IP trực tiếp.</p>
      <div class="bulk-grid"><div><label for="bulk-items">Domain List</label><textarea id="bulk-items" placeholder="zenbooks.vn\nexample.vn,1.2.3.4\ncompany.com"></textarea><div class="hint">Mỗi dòng một domain. Có thể dùng <b>domain,wan_ip</b>.</div></div></div>
      <div class="actions"><button id="bulk-run" class="primary" type="button">▶ Run Bulk Audit</button><button id="bulk-clear" type="button">Clear List</button></div>
    </section>
  </div>
  <div id="result" style="margin-top:20px"></div><div id="bulk-result" style="margin-top:20px"></div>
</div>
<script>
const csrf=document.querySelector('[name=_token]').value;
const esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
const arr=v=>Array.isArray(v)?v:[];const val=(v,f='—')=>(v===null||v===undefined||v==='')?f:v;
const days=v=>{if(v===null||v===undefined||v==='')return'N/A';const n=Number(v);return Number.isFinite(n)?Math.floor(n).toLocaleString('en-US')+' days':String(v)};const bool=v=>v===true?'YES':v===false?'NO':'—';
function kv(items){return '<div class="kv">'+items.map(([k,v])=>`<b>${esc(k)}</b><span>${esc(v)}</span>`).join('')+'</div>'}function card(title,items){return `<div class="audit-card"><h4>${title}</h4>${kv(items)}</div>`}
function recordsTable(records){let rows=[];Object.entries(records||{}).forEach(([type,list])=>arr(list).forEach(r=>{const copy={...r};delete copy.type;rows.push([type,Object.entries(copy).map(([k,v])=>k+'='+v).join(' · ')])}));if(!rows.length)return '<div class="notice">No DNS records returned.</div>';return '<div style="overflow:auto"><table class="records"><thead><tr><th>Type</th><th>Record</th></tr></thead><tbody>'+rows.map(r=>`<tr><td><b>${esc(r[0])}</b></td><td class="mono">${esc(r[1])}</td></tr>`).join('')+'</tbody></table></div>'}
function renderSingle(a){const d=a.domain_audit||{},dns=a.dns_audit||{},s=a.ssl_audit||{},w=a.website_audit||{},h=w.http||{},hs=w.https||{},e=a.email_audit||{},i=a.ip_audit||{},p=a.provider_detection||{},sv=a.service_discovery||{};const services=arr(sv.services),online=services.filter(x=>x.status==='online').length,dnsOnly=services.filter(x=>x.status==='dns_only').length,notFound=services.filter(x=>x.status==='not_found').length;const overall=(d.status==='ok'||d.status==='available')&&s.status==='ok'&&hs.online;const dkim=Object.entries(e.dkim||{}).map(([k,v])=>k+': '+(v.present?'PASS':'MISSING')).join('; ')||'Not checked';const found=arr(dns.record_types_found).join(', ')||'—';document.getElementById('result').innerHTML=`<section class="panel"><div class="result-head"><div><h3>Audit Result — ${esc(a.domain)}</h3><p class="sub">Checked: ${esc(a.checked_at||'—')}</p></div><span class="score ${overall?'ok':'warn'}">${overall?'● AUDIT OK':'● REVIEW REQUIRED'}</span></div><div class="cards">
${card('🌐 Domain',[['Status',val(d.status)],['Registrar',val(d.registrar)],['Created',val(d.created_at)],['Expiry',val(d.expires_at,'N/A')],['Days Left',days(d.days_remaining)],['Source',val(d.source)],['Nameservers',arr(d.nameservers).join(', ')||'—']])}
${card('🔐 SSL / TLS',[['Status',val(s.status)],['Vendor',val(s.vendor,'N/A')],['Subject',val(s.subject)],['Issuer',val(s.issuer)],['Valid From',val(s.valid_from)],['Valid To',val(s.valid_to,'N/A')],['Days Left',days(s.days_remaining)],['Hostname Match',bool(s.verify)],['TLS Version',val(s.tls_version)],['Cipher',val(s.cipher)]])}
${card('🖥 Website',[['HTTP',val(h.status)],['HTTP Online',bool(h.online)],['HTTP Response',val(h.response_time_ms)+' ms'],['HTTPS',val(hs.status)],['HTTPS Online',bool(hs.online)],['HTTPS Response',val(hs.response_time_ms)+' ms'],['HTTPS Final URL',val(hs.final_url)],['Transport Verified',bool(hs.transport_verified)],['HSTS',bool(hs.hsts)]])}
${card('☁ IP / Hosting',[['Primary IP',val(i.ip,'N/A')],['Resolved IPv4',arr(a.resolved_ipv4).join(', ')||'—'],['ASN',val(i.asn)],['Network',val(i.network)],['Organization',val(i.organization)],['IP Provider',val(i.provider)],['Hosting Provider',val(p.hosting_provider)],['CDN',val(p.cdn)],['WAF',val(p.waf)]])}
${card('✉ Email Security',[['Mail Provider',val(e.provider,'N/A')],['MX Count',arr(e.mx).length],['SPF',e.spf_present?'PASS':'MISSING'],['DMARC',e.dmarc_present?'PASS':'MISSING'],['DKIM',dkim],['MTA-STS',e.mta_sts_present?'PASS':'MISSING'],['TLS-RPT',e.tls_rpt_present?'PASS':'MISSING']])}
${card('🧭 DNS Summary',[['Provider',val(dns.dns_provider,'N/A')],['Provider Source',val(dns.dns_provider_source)],['Nameservers',arr(dns.dns_nameservers).join(', ')||'N/A'],['DNSSEC',dns.dnssec?'DETECTED':'NOT DETECTED'],['Found Types',found],['Query Mode',val(dns.dns_query_mode)]])}</div>
<details class="section" open><summary>DNS Records — All Returned RRsets</summary><div class="section-body"><div class="notice">Backend queries common RR types and merges <b>DNS_ALL</b> results. This shows all records returned for the audited domain name; it does not enumerate unknown subdomains/selectors.</div><div style="margin-top:10px">${recordsTable(dns.records||{})}</div></div></details>
<details class="section"><summary>Website Security Headers</summary><div class="section-body"><table class="records"><thead><tr><th>Protocol</th><th>Security Headers</th></tr></thead><tbody>${['https','http'].map(k=>`<tr><td><b>${k.toUpperCase()}</b></td><td class="mono">${esc(Object.entries((w[k]||{}).headers||{}).map(([x,y])=>x+': '+(y||'MISSING')).join('\n')||'No header data')}</td></tr>`).join('')}</tbody></table></div></details>
<details class="section"><summary>Service Discovery — ${services.length} Hosts</summary><div class="section-body"><div class="statusbar"><span class="pill"><strong>${services.length}</strong> checked</span><span class="pill">Online: <strong>${online}</strong></span><span class="pill">DNS only: <strong>${dnsOnly}</strong></span><span class="pill">Not found: <strong>${notFound}</strong></span></div><div class="service-table" style="margin-top:10px"><table class="records"><thead><tr><th>Hostname</th><th>IPs</th><th>HTTP</th><th>HTTPS</th><th>Status</th></tr></thead><tbody>${services.map(x=>`<tr><td class="mono">${esc(x.hostname)}</td><td class="mono">${esc(arr(x.ips).join(', ')||'—')}</td><td>${esc(val(x.http?.status))}</td><td>${esc(val(x.https?.status))}</td><td><b>${esc(String(x.status||'').toUpperCase())}</b></td></tr>`).join('')}</tbody></table></div></div></details></section>`;document.getElementById('result').scrollIntoView({behavior:'smooth',block:'start'})}
async function requestAudit(item){const r=await fetch('{{ route('admin.it_tools.audit') }}',{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json','X-CSRF-TOKEN':csrf,'X-Requested-With':'XMLHttpRequest'},body:JSON.stringify({domain:item.domain,wan_ip:item.wan_ip||null,dkim_selectors:item.dkim_selectors||null,service_hosts:item.service_hosts||null})});const text=await r.text();let data={};try{data=text?JSON.parse(text):{}}catch(_){throw new Error('Server returned non-JSON response (HTTP '+r.status+').')}if(!r.ok)throw new Error(data.message||('Audit failed (HTTP '+r.status+')'));return data}
document.getElementById('audit-form').addEventListener('submit',async ev=>{ev.preventDefault();const domain=document.getElementById('domain').value.trim();if(!domain)return;const loading=document.getElementById('single-loading');loading.style.display='block';document.getElementById('result').innerHTML='';try{renderSingle(await requestAudit({domain,wan_ip:document.getElementById('wan_ip').value.trim(),dkim_selectors:document.getElementById('dkim_selectors').value.trim(),service_hosts:document.getElementById('service_hosts').value.trim()}))}catch(e){document.getElementById('result').innerHTML=`<div class="panel"><span class="score bad">● ERROR</span><p>${esc(e.message)}</p></div>`}finally{loading.style.display='none'}});document.getElementById('clear-single').addEventListener('click',()=>{['domain','wan_ip','dkim_selectors','service_hosts'].forEach(id=>document.getElementById(id).value='');document.getElementById('result').innerHTML=''});
function parseBulkText(text){return text.split(/\r?\n/).map(x=>x.trim()).filter(Boolean).map(line=>{const parts=line.split(',').map(x=>x.trim());return{domain:parts[0],wan_ip:parts[1]||null}})}
function serviceSummary(s){const rows=arr(s?.services);return{checked:s?.checked_hosts??rows.length,online:rows.filter(x=>x.status==='online').length,dnsOnly:rows.filter(x=>x.status==='dns_only').length,notFound:rows.filter(x=>x.status==='not_found').length,summary:rows.map(x=>(x.hostname||x.label||'unknown')+'='+String(x.status||'unknown').toUpperCase()).join('; ')||'—'}}
function bv(item){const a=item.audit||{},d=a.domain_audit||{},s=a.ssl_audit||{},w=a.website_audit||{},h=w.http||{},hs=w.https||{},i=a.ip_audit||{},e=a.email_audit||{},dns=a.dns_audit||{},p=a.provider_detection||{},sv=serviceSummary(a.service_discovery);return{checked:a.checked_at,domain:item.domain,wan:item.wan_ip||a.wan_ip_supplied||'—',status:item.status==='ok'?'OK':'ERROR',de:d.expires_at||'N/A',dd:days(d.days_remaining),ds:d.source||'—',http:h.status??'—',ho:bool(h.online),hu:h.final_url||'—',hr:h.response_time_ms??'—',hs:hs.status??'—',hso:bool(hs.online),hsu:hs.final_url||'—',sv:s.vendor||'N/A',se:s.valid_to||'N/A',sd:days(s.days_remaining),hm:bool(s.verify),ip:i.ip||'N/A',net:i.network||'—',asn:i.asn||'—',ipp:i.provider||'—',dp:dns.dns_provider||p.dns_provider||'N/A',ns:arr(dns.dns_nameservers).join(', ')||'N/A',sec:dns.dnssec?'DETECTED':'NOT DETECTED',types:arr(dns.record_types_found).join(', ')||'—',mx:arr(e.mx).length,mail:e.provider||'N/A',spf:e.spf_present?'PASS':'MISSING',dm:e.dmarc_present?'PASS':'MISSING',dk:Object.entries(e.dkim||{}).map(([k,v])=>k+': '+(v.present?'PASS':'MISSING')).join('; ')||'Not checked',mta:e.mta_sts_present?'PASS':'MISSING',rpt:e.tls_rpt_present?'PASS':'MISSING',cdn:p.cdn||'—',waf:p.waf||'—',host:p.hosting_provider||'—',sc:sv.checked,so:sv.online,sn:sv.notFound,ss:sv.summary,error:item.error||''}}
function bulkRow(item){const v=bv(item),td=(x,c='')=>`<td class="${c}">${esc(x)}</td>`;return `<tr>${td(v.checked)}${td(v.domain)}${td(v.wan)}${td(v.status,v.status==='OK'?'ok':'bad')}${td(v.de)}${td(v.dd)}${td(v.ds)}${td(v.http)}${td(v.ho)}${td(v.hu,'wrap')}${td(v.hr)}${td(v.hs)}${td(v.hso)}${td(v.hsu,'wrap')}${td(v.sv)}${td(v.se)}${td(v.sd)}${td(v.hm)}${td(v.ip)}${td(v.net)}${td(v.asn)}${td(v.ipp)}${td(v.dp)}${td(v.ns,'wrap')}${td(v.sec)}${td(v.types)}${td(v.mx)}${td(v.mail)}${td(v.spf)}${td(v.dm)}${td(v.dk,'wrap')}${td(v.mta)}${td(v.rpt)}${td(v.cdn)}${td(v.waf)}${td(v.host)}${td(v.sc)}${td(v.so)}${td(v.sn)}${td(v.ss,'wrap')}${td(v.error,'wrap')}</tr>`}
function renderBulk(results,total){const groups=[['Audit',4,''],['Domain',3,''],['Website / HTTP',4,'web'],['Website / HTTPS',4,'web'],['SSL / TLS',4,'ssl'],['IP / Hosting',4,'ip'],['DNS Summary',5,'dns'],['Email Security',7,'mail'],['Provider / Service Discovery',7,'provider'],['Error',1,'error']];const hs=['Checked At','Domain','WAN IP','Status','Domain Expiry','Domain Days','Domain Source','HTTP Status','HTTP Online','HTTP Final URL','HTTP ms','HTTPS Status','HTTPS Online','HTTPS Final URL','SSL Vendor','SSL Expiry','SSL Days','Hostname','Primary IP','Network','ASN','IP Provider','DNS Provider','Nameservers','DNSSEC','Record Types','MX','Mail Provider','SPF','DMARC','DKIM','MTA-STS','TLS-RPT','CDN','WAF','Hosting Provider','Services Checked','Services Online','Services Not Found','Service Summary','Error'];document.getElementById('bulk-result').innerHTML=`<section class="panel"><div class="result-head"><div><h3>Bulk Result</h3><p class="sub">${results.length} / ${total} completed · DNS summary only</p></div></div><div class="bulk-table-wrap"><table class="bulk-table"><thead><tr class="group">${groups.map(g=>`<th colspan="${g[1]}" class="${g[2]}">${g[0]}</th>`).join('')}</tr><tr>${hs.map(x=>`<th>${esc(x)}</th>`).join('')}</tr></thead><tbody>${results.map(bulkRow).join('')}</tbody></table></div></section>`}
async function runBulk(){const items=parseBulkText(document.getElementById('bulk-items').value);if(!items.length){alert('Please enter at least one domain.');return}const btn=document.getElementById('bulk-run');btn.disabled=true;btn.textContent='Running...';document.getElementById('bulk-result').innerHTML='<section class="panel"><span class="score warn">● RUNNING</span><p>Đang audit '+items.length+' domain...</p></section>';try{const r=await fetch('{{ route('admin.it_tools.bulk_audit') }}',{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json','X-CSRF-TOKEN':csrf,'X-Requested-With':'XMLHttpRequest'},body:JSON.stringify({items})});const data=await r.json();if(!r.ok)throw new Error(data.message||('Bulk audit failed (HTTP '+r.status+')'));renderBulk(data.results||[],data.requested||items.length)}catch(e){document.getElementById('bulk-result').innerHTML=`<section class="panel"><span class="score bad">● ERROR</span><p>${esc(e.message)}</p></section>`}finally{btn.disabled=false;btn.textContent='▶ Run Bulk Audit'}}
document.getElementById('bulk-run').addEventListener('click',runBulk);document.getElementById('bulk-clear').addEventListener('click',()=>{document.getElementById('bulk-items').value='';document.getElementById('bulk-result').innerHTML=''})
</script>
@endsection
