@extends('layouts.admin')
@section('title','IT Monitoring - Alert Events')
@section('content')
<div class="actions" style="justify-content:space-between;margin-bottom:16px">
    <div><h2 style="margin:0">Alert Events</h2><div class="muted">Current alert events generated by IT Monitoring. No check history is stored.</div></div>
</div>

<div class="card">
    <form method="get" class="actions" style="margin-bottom:12px">
        <label>Status
            <select name="status">
                <option value="">All</option>
                @foreach(['open','acknowledged','resolved'] as $value)
                    <option value="{{ $value }}" @selected($status === $value)>{{ ucfirst($value) }}</option>
                @endforeach
            </select>
        </label>
        <button class="btn" type="submit">Filter</button>
    </form>
    <div class="table-wrap"><table class="table">
        <thead><tr><th>Triggered</th><th>Service</th><th>Alert</th><th>Remaining</th><th>Expiry</th><th>Status</th><th>Action</th></tr></thead>
        <tbody>
        @forelse($events as $event)
            <tr>
                <td>{{ optional($event->triggered_at)->format('d/m/Y H:i') }}</td>
                <td>{{ $event->service?->service_name ?? '-' }}</td>
                <td>{{ $event->alert_stage == 4 ? 'Expired' : 'Alert '.$event->alert_stage }}</td>
                <td>{{ $event->remaining_percent }}%</td>
                <td>{{ optional($event->expiry_date)->format('d/m/Y') }}</td>
                <td>{{ ucfirst($event->status) }}</td>
                <td>
                    @if($event->status === 'open')
                        <form method="post" action="{{ route('admin.service_alert_events.acknowledge',$event) }}" style="display:inline">@csrf<button class="btn" type="submit">Acknowledge</button></form>
                    @endif
                    @if($event->status !== 'resolved')
                        <form method="post" action="{{ route('admin.service_alert_events.resolve',$event) }}" style="display:inline">@csrf<button class="btn" type="submit">Resolve</button></form>
                    @endif
                </td>
            </tr>
        @empty
            <tr><td colspan="7" class="muted">No alert events found.</td></tr>
        @endforelse
        </tbody>
    </table></div>
    <div style="margin-top:12px">{{ $events->links() }}</div>
</div>
@endsection
